# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: cd '$(System.DefaultWorkingDirectory)'
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      npm i bower
- task: WhiteSource@20
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Bower'
